const fs = require("fs");
const path = require("path");

const configFile = path.join("../../../sitemap.config.js");

if (!fs.existsSync(configFile)) {
  const defaultConfig = `
// Auto-generated by @haspcms/sitemap
require("dotenv").config(); // load .env at the very top

const { generateSitemap, setConfig } = require("@haspcms/sitemap");

const envVars = {
  HASP_TENANT_API: process.env.HASP_TENANT_API,
  HASP_RATE_LIMIT_KEY: process.env.HASP_RATE_LIMIT_KEY, 
  HASP_MICROSITE_ID: process.env.HASP_MICROSITE_ID,
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  HASP_CONTENT_TYPES: process.env.HASP_CONTENT_TYPES,
  HASP_TENANT_API_KEY: process.env.HASP_TENANT_API_KEY,
  HASP_TENANT_SECRET_KEY: process.env.HASP_TENANT_SECRET_KEY,
  HASP_TENANT_STRICT_API_ENABLED: process.env.HASP_TENANT_STRICT_API_ENABLED,
};

setConfig(envVars);

(async () => {
  try {
    await generateSitemap({ 
      outDir: "./public",
      siteUrl: envVars.NEXT_PUBLIC_SITE_URL,
      sitemapSize: 5000, 
    });
    console.log("✅ Sitemap generated successfully!");
  } catch (err) {
    console.error("❌ Sitemap generation failed:", err);
  }
})();
`;

  fs.writeFileSync(configFile, defaultConfig.trim() + "\n");
  console.log("✅ Created sitemap.config.js in project root:", configFile);
} else {
  console.log("ℹ️ sitemap.config.js already exists, skipping...");
}
